### ISSUE TITLE
是否具有绝对尺度？

### ISSUE THREAD

**Issue by OpenAskDragon** [huziqi/NALO-SLAM#1]
您好，我想问一下该算法在实际运行的过程中实际上是一个单目的视觉里程计，不能得到所建立地图的绝对尺度（例如米制单位），对吗

**Comment by huziqi** [comment]
> 您好，我想问一下该算法在实际运行的过程中实际上是一个单目的视觉里程计，不能得到所建立地图的绝对尺度（例如米制单位），对吗

是的，该算法只能保证在相对尺度空间的一致性。
